### ISSUE TITLE
handle failed downloads

### ISSUE THREAD

**Issue by tortino** [aesqe/firefox-downloads-sidebar#15]
hello,
the extension does not handle correctly failed downloads: when a download fails I see in the sidebar the message "calculating", instead it should be "failed" or something similar.
Also when I restart the download (using the default firefox downloads toolbar icon) the message still says "calculating" and is not updated (workaround: close and reopen the sidebar).
thanks.

**Comment by josalhor** [comment]
I probably messed something up.

When you say failed you don't mean cancelling the download, you mean the server or the client fail to communicate anymore, right?

**Comment by tortino** [comment]
yes, I didn't manually canceled the download, the server failed.

**Comment by josalhor** [comment]
Actually, i think I didn't mess anything up, I believe that case was not handled in the first place. That pull request should fix it.

**Comment by tortino** [comment]
ok thanks!
