### ISSUE TITLE
about:downloads in sidebar

### ISSUE THREAD

**Issue by maverick74** [aesqe/firefox-downloads-sidebar#3]
hi @aesqe 

can't the addon include the page about:downloads already native in FF, and start from there?

I ask this without knowing much about addons... it's just an idea!

(About my review on AMO: no need to thank me! I really don't get why isn't this already native in FF. Sidebar is a logic evolution. Thank You for your work!!! :) )

**Comment by aesqe** [comment]
@maverick74 good idea, I've tried it, but it doesn't work, unfortunately :/ It's either a security or implementation issue.

I suppose Mozilla will add downloads to the sidebar some day, I don't know why they're not an option there, either :)

**Comment by maverick74** [comment]
i see...

ok, then this bug does not make sense anymore. I'll close it and wait for your update :)

Thank you :)
