### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by rayman89** [aesqe/firefox-downloads-sidebar#4]
I noticed that the download sidebar is not showing the download speed could you add that please?

**Comment by aesqe** [comment]
@rayman89 I'll add it in v0.5, probably this week

**Comment by josalhor** [comment]
This was added already, right?

I think you should close this issue.

**Comment by josalhor** [comment]
My fault, you're right, I mistook it for the download progress. This weekend I will take a look at it. No promises.

**Comment by josalhor** [comment]
I'm very happy to announce that today I got remaining speed and remaining time working on my branch with the visual changes. See #12 .

When we merge you will see the changes too.

**Comment by arelkin** [comment]
Great work on the sidebar. Excellent that it also includes bookmarks, history and other FF chrome as options to be viewed.

I just installed and noticed that the download rate registered as "<0 MB/s" when I was d/l at a rate of (admittedly slow) 158k/s. (see screengrab)
You should allow users the option to view d/l rate in either k/s or MB/s.

![side-dowload-rate](https://user-images.githubusercontent.com/213207/57264575-a5007800-7040-11e9-99a6-61bdc6c809ba.jpg)

**Comment by josalhor** [comment]
At the time I didn't think it was a big deal. I wanted to keep my changes simple. You're probably right that it should display something else than MB/s, but that certainly complicates the system a little bit more. Next week I'll take a look at it when I come back from a Congress.

However, I disagree that users should pick the metric. It should be completely transparent to the user.

**Comment by harl** [comment]
Good to know this is still being considered.
Please at least make it say "<1 MB/s" (which is practically always the case for many people btw).

**Comment by josalhor** [comment]
Yeah sorry again for the delay, I'm with exams right now.
I already have the design of how to implement this in my mind, I just have to find some time to actually do it and send a pull request.
My exams finish on June 7, so expect a PR around that date.

**Comment by harl** [comment]
Good luck with those exams. Qapla'!

**Comment by josalhor** [comment]
#14 Pull Request merges the changes I had in mind

**Comment by aesqe** [comment]
#14 is merged and v1.0 of the extension is now available https://addons.mozilla.org/en-US/firefox/addon/downloads-sidebar/
