### ISSUE TITLE
Estimated Time of Arrival

### ISSUE THREAD

**Issue by vikingil** [aesqe/firefox-downloads-sidebar#6]
Nice Add-On.
1. Can you please add the estimated time the download will be completed? it is shown in the regular download menu...
2. The date I see is always 1/1/1970 2:00:00 AM for all downloads, should I configure something to see the actual date?

**Comment by josalhor** [comment]
Great news, when #12 merges you'll get the estimated time of arrival.

**Comment by josalhor** [comment]
Even more good news, #14 should now fix completly the 1970 epoch bug!

**Comment by aesqe** [comment]
#14 is merged and v1.0 of the extension is now available https://addons.mozilla.org/en-US/firefox/addon/downloads-sidebar/
